#! /bin/sh
sudo ldconfig
sudo chmod -R 777 /usr/share/ibus-braille/braille/
if [ -x "`which update-menus 2>/dev/null`" ]; then
sudo update-menus
fi

if [ -x "`which update-desktop-database 2>/dev/null`" ]; then
sudo update-desktop-database
fi
